import "./globals.css";
import { UserProvider } from "../Context/UserContext";
import { DataProvider } from "@/Context/DataContext";
import NavBar from "../components/NavBar";

export const metadata = {
  title: "Wabau learn",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-[#0c0f0e] overflow-x-hidden flex flex-col">
        <DataProvider>
          <NavBar />
          <UserProvider>{children}</UserProvider>
        </DataProvider>
      </body>
    </html>
  );
}
