import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "./../Context/UserContext";
import { DataProvider } from "@/Context/DataContext";

export const metadata: Metadata = {
  title: "Wabau learn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-[#0c0f0e] overflow-x-hidden flex flex-col">
        <DataProvider>
          <UserProvider>{children}</UserProvider>
        </DataProvider>
      </body>
    </html>
  );
}
